[package]
name = "aglet-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
aglet-pretty = { path = "../aglet-pretty" }
aglet-text = { path = "../aglet-text" }
syn = { version = "2.0.37", features = ["derive"] }
quote = "1.0"