unstable_features = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
struct_field_align_threshold = 50