[package]
name = "aglet-text"
version = "0.1.0"
authors = ["Carson Myers <carson@myers.se>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
